version: '3.8'
services:
  shiny-app:
    build: .
    container_name: shiny-app-container  
    ports:
      - ":3838"
    networks:
      - default_bridge  # Reference the existing bridge network

networks:
  default_bridge:
    external:
      name: bridge  # Use the predefined bridge network