version: '3.8'
services:
  shiny-app:
    image: nicolemah99/shiny-app-example:latest
    ports:
      - ":3838"
    volumes:
      - shiny-app-data:/srv/shiny-server
    networks:
      - shiny-network

networks:
  shiny-network:
    driver: bridge

volumes:
  shiny-app-data:
