version: '3.8'

services:
  shiny:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3838"
    volumes:
      - ./example-app:/srv/shiny-server/example-app
    restart: always
